<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
// session_start();

// if ($_SESSION['status'] != "Active") {
//     header("location:../Login/dist/login.php");
// }
require_once 'arangodb_connection.php';

use ArangoDBClient\Statement as ArangoStatement;
use ArangoDBClient\DocumentHandler as ArangoDocumentHandler;
use ArangoDBClient\CollectionHandler as ArangoCollectionHandler;

$documentHandler = new ArangoDocumentHandler($connection);
$collectionHandler = new ArangoCollectionHandler($connection);

$queryBusNo = 'FOR b IN busDetails RETURN DISTINCT b.bus_no';
$statementBusNo = new ArangoStatement($connection, ['query' => $queryBusNo, '_flat' => true]);
$bus_nos = $statementBusNo->execute()->getAll();

$querySource = 'FOR b IN busDetails RETURN DISTINCT b.Source';
$statementSource = new ArangoStatement($connection, ['query' => $querySource, '_flat' => true]);
$Source = $statementSource->execute()->getAll();

$queryDestination = 'FOR b IN busDetails RETURN DISTINCT b.Destination';
$statementDestination = new ArangoStatement($connection, ['query' => $queryDestination, '_flat' => true]);
$Destination = $statementDestination->execute()->getAll();

$queryDriverId = 'FOR t IN tripIncharge RETURN DISTINCT t.Driver_emp_id';
$statementDriverId = new ArangoStatement($connection, ['query' => $queryDriverId, '_flat' => true]);
$Driver_emp_id = $statementDriverId->execute()->getAll();

$queryConductorId = 'FOR t IN tripIncharge RETURN DISTINCT t.Conductor_emp_id';
$statementConductorId = new ArangoStatement($connection, ['query' => $queryConductorId, '_flat' => true]);
$Conductor_emp_id = $statementConductorId->execute()->getAll();

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="tripDetails.css">

    <title>Conductor Trip Details</title>
</head>

<body id="grad" class="grad">
    <a class="button" href="../Login/dist/logout.php">Log Out</a>
    <a class="button" href="AdminDashboard.php">Go Back</a>
    <div class="maindiv" id="maindiv">

        <form align="center" action="SuperAdmin.php" method="post">
            <div class="title">

                <h2>Enter Trip Details</h2>
            </div>

            <div class="info">

                <!-- Trip Number: <input type="number" placeholder="Trip Number" name="TripNumber"><br><br> ..this is being autogenerated -->
                Bus Number: <select placeholder="Bus Number" name="BusNumber"><br><br>
                    <?php
                    foreach ($bus_nos as $bus_no):
                    ?>
                    <option value="<?php echo $bus_no; ?>">
                        <?php echo $bus_no; ?>
                    </option>
                    <?php
                    endforeach;
                    ?>
                </select><br><br>






                Source: <select placeholder="Source" name="Source">
                    <?php
                    foreach ($Source as $source_val):
                    ?>
                    <option value="<?php echo $source_val; ?>">
                        <?php echo $source_val; ?>
                    </option>
                    <?php
                    endforeach;
                    ?>
                </select><br><br>



                Destination: <select placeholder="Destination" name="Destination">
                    <?php
                    foreach ($Destination as $destination_val):
                    ?>
                    <option value="<?php echo $destination_val; ?>">
                        <?php echo $destination_val; ?>
                    </option>
                    <?php
                    endforeach;
                    ?>
                </select><br><br>





                Date: <input type="date" placeholder="Date" name="Date"><br><br>
                Scheduled Departure: <input type="time" placeholder="Destination" name="sdep"><br><br>
                Scheduled Arriival: <input type="time" placeholder="Date" name="sarr"><br><br>
                Driver ID: <select placeholder="Driver ID" name="did">
                    <?php
                    foreach ($Driver_emp_id as $driver_id_val):
                    ?>
                    <option value="<?php echo $driver_id_val; ?>">
                        <?php echo $driver_id_val; ?>
                    </option>
                    <?php
                    endforeach;
                    ?>
                </select><br><br>




                ConductorID: <select placeholder="Conductor id" name="cid">
                    <?php
                    foreach ($Conductor_emp_id as $conductor_id_val):
                    ?>
                    <option value="<?php echo $conductor_id_val; ?>">
                        <?php echo $conductor_id_val; ?>
                    </option>
                    <?php
                    endforeach;
                    ?>
                </select><br><br>




            </div>

            <br>

            <button type="submit">Submit</button>
        </form>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

    <script>
        $(function () {
            $(document).scroll(function () {
                var $nav = $("#mainNavbar");
                $nav.toggleClass("scrolled", $(this).scrollTop() > $nav.height());
            });
        });
    </script>
</body>

</html>
