<?php
require_once 'arangodb_connection.php';

use ArangoDBClient\Statement as ArangoStatement;
use ArangoDBClient\DocumentHandler as ArangoDocumentHandler;
use ArangoDBClient\Document as ArangoDocument;
use ArangoDBClient\CollectionHandler as ArangoCollectionHandler;

$documentHandler = new ArangoDocumentHandler($connection);
$collectionHandler = new ArangoCollectionHandler($connection);

// get the post records
$BusNumber = $_POST['BusNumber'];
$Source = $_POST['Source'];
$Destination = $_POST['Destination'];
$Date = $_POST['Date'];
//trip_incharge_post_combine
$did = $_POST['did'];
$cid = $_POST['cid'];
$sdep = $_POST['sdep'];
$sarr = $_POST['sarr'];

//generating trip id
$query = 'FOR b IN busDetails SORT b.trip_no DESC LIMIT 1 RETURN b.trip_no';
$statement = new ArangoStatement($connection, ['query' => $query, '_flat' => true]);
$cursor = $statement->execute();
$lastTripNo = $cursor->current();

$tripNO = ($lastTripNo !== null) ? $lastTripNo + 1 : 1;
?>





// database insert for Bus_details
$busDetailsDocument = new ArangoDocument();
$busDetailsDocument->set('trip_no', (int)$tripNO);
$busDetailsDocument->set('bus_no', (int)$BusNumber);
$busDetailsDocument->set('Source', $Source);
$busDetailsDocument->set('Destination', $Destination);
$busDetailsDocument->set('TripDate', $Date);

try {
    $documentHandler->save('busDetails', $busDetailsDocument);
} catch (ArangoDBClient\Exception $e) {
    echo "Error inserting bus details: " . $e->getMessage();
}

// database insert for trip_incharge
$tripInchargeDocument = new ArangoDocument();
$tripInchargeDocument->set('trip_no_incharge', (int)$tripNO);
$tripInchargeDocument->set('Driver_emp_id', $did);
$tripInchargeDocument->set('Conductor_emp_id', $cid);
$tripInchargeDocument->set('scheduled_dept_time', $sdep);
$tripInchargeDocument->set('scheduled_arr_time', $sarr);

try {
    $documentHandler->save('tripIncharge', $tripInchargeDocument);
    echo "<p style='color:#EA1C2C;margin:70px 0px 0px 0px;'>Trip number generated Successfully. Trip Number is '{$tripNO}'.</p>";
} catch (ArangoDBClient\Exception $e) {
    echo "Error inserting trip incharge details: " . $e->getMessage();
}
?>


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Conductor Trip Details</title>
    <link rel="icon" type="image/x-icon" href="../Images/icon1.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="../Login/dist/style.css">
    <link rel="stylesheet" type="text/css" href="tripDetails.css">
    <style>
        body {
            background: url("../Images/bus_huit.png") no-repeat center;
            background-size: cover;

        }
    </style>
</head>

<body>
    <nav id="mainNavbar" class="navbar navbar-light navbar-expand-md py-1 px-2 fixed-top"
        style="background-color: #0cb2f9;">
        <a class="navbar-brand" href="#">
            <img src="../Images/icon1.png" width="45" height="35" class="d-inline-block align-middle" alt="">
            BUS MANAGEMENT SYSTEM
        </a>

        <button class="navbar-toggler" data-toggle="collapse" data-target="#navLinks" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-between" id="navLinks">


            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="AdminDashboard.php" class="nav-link">HOME</a>
                </li>
                <li class="nav-item">
                    <a href="../about.html" class="nav-link">ABOUT</a>
                </li>
                <li class="nav-item">
                    <a href="../team.html" class="nav-link">TEAM</a>
                </li>


            </ul>
            <span class="nav-item ml-auto">
                <a class="nav-link" role="button" href="AdminDashboard.php">Go Back</a>
            </span>
            <span class="nav-item">
                <a class="nav-link" role="button" href="../Login/dist/logout.php">Logout</a>
            </span>


        </div>
    </nav>
    <div class="maindiv" id="maindiv" style="width: 40%; margin:10px;">

        <form action="SuperAdmin.php" method="post">
            <div class="title">

                <h2 class="text-center">Enter Trip Details</h2>
            </div>
            <br>
            <div class="info">

                <!-- Trip Number: <input type="number" placeholder="Trip Number" name="TripNumber"><br><br> ..this is being autogenerated -->

                <div class="form-group row">
                    <div class="col">
                        <label for="totalRevenue">Bus Number:</label>
                        <input class="form-control" input type="number" placeholder="Bus Number" name="BusNumber"
                            required>

                    </div>
                    <div class="col">
                        <label for="Date">Date: </label>
                        <input class="form-control" type="date" placeholder="Date" name="Date" required style="border-radius: 10px;
                    box-shadow: 5px 5px 5px #aaaaaa;">

                    </div>



                </div>
                <div class="form-group row">

                    <div class="col">
                        <label for="BusNumber">Source: </label>
                        <input class="form-control" type="text" placeholder="Source" name="Source" required>
                    </div>
                    <div class="col">
                        <label for="totalRevenue">Destination: </label>
                        <input class="form-control" type="text" placeholder="Destination" name="Destination" required>

                    </div>


                </div>

                <div class="form-group row">

                    <div class="col">
                        <label for="sdep">Scheduled Departure: </label>
                        <input class="form-control" type="time" placeholder="Destination" name="sdep" required>
                    </div>
                    <div class="col">
                        <label for="sarr">Scheduled Arrival: </label>
                        <input class="form-control" type="time" placeholder="Date" name="sarr" required>

                    </div>


                </div>

                <div class="form-group row">

                    <div class="col">
                        <label for="did">Driver ID: </label>
                        <input class="form-control" type="text" placeholder="Driver ID" name="did" required>
                    </div>
                    <div class="col">
                        <label for="cid">Conductor ID: </label>
                        <input class="form-control" type="text" placeholder="Conductor id" name="cid" required>

                    </div>


                </div>
            </div>

            <br>

            <button type="submit">Submit</button>
        </form>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

    <script>
        $(function () {
            $(document).scroll(function () {
                var $nav = $("#mainNavbar");
                $nav.toggleClass("scrolled", $(this).scrollTop() > $nav.height());
            });
        });
    </script>

</body>

</html>
